apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-to-do-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-to-do-app
  template:
    metadata:
      labels:
        app: react-to-do-app
    spec:
      containers:
      - name: react-to-do-app
        image: amrudesh072/react-to-do-app
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: react-to-do-app
spec:
  selector:
    app: react-to-do-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

